//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacao.Models.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_Cargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAR_Cargo()
        {
            this.USU_Usuario = new HashSet<USU_Usuario>();
        }
    
        public int CAR_ID { get; set; }
        public string CAR_DESCRICAO { get; set; }
        public Nullable<System.DateTime> CAR_DataCadastro { get; set; }
        public Nullable<System.DateTime> CAR_DataAlteracao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USU_Usuario> USU_Usuario { get; set; }
    }
}
