//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacao.Models.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class DES_Desempenho
    {
        public int DES_ID { get; set; }
        public Nullable<int> GRC_ID { get; set; }
        public Nullable<int> USU_ID { get; set; }
        public Nullable<int> DSF_ID { get; set; }
        public double DES_Valor { get; set; }
        public Nullable<System.DateTime> DES_DataCadastro { get; set; }
        public Nullable<System.DateTime> DES_DataAlteracao { get; set; }
        public string DES_Anotacao { get; set; }
        public Nullable<int> DSD_ID { get; set; }
        public Nullable<int> DSK_ID { get; set; }
    
        public virtual DSF_DesempenhoFase DSF_DesempenhoFase { get; set; }
        public virtual GRC_GrupoCompeticao GRC_GrupoCompeticao { get; set; }
        public virtual USU_Usuario USU_Usuario { get; set; }
        public virtual DSD_DesempenhoDescricao DSD_DesempenhoDescricao { get; set; }
        public virtual DSK_DesempenhoKpi DSK_DesempenhoKpi { get; set; }
    }
}
