//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacao.Models.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSD_DesempenhoDescricao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DSD_DesempenhoDescricao()
        {
            this.DES_Desempenho = new HashSet<DES_Desempenho>();
        }
    
        public int DSD_ID { get; set; }
        public string DSD_Nome { get; set; }
        public string DSD_Display { get; set; }
        public string DSD_Prefixo { get; set; }
        public string DSD_Sufixo { get; set; }
        public Nullable<System.DateTime> DSD_DataCadastro { get; set; }
        public Nullable<System.DateTime> DSD_DataAlteracao { get; set; }
        public string DSD_Anotacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DES_Desempenho> DES_Desempenho { get; set; }
    }
}
