//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacao.Models.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSK_DesempenhoKpi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DSK_DesempenhoKpi()
        {
            this.DES_Desempenho = new HashSet<DES_Desempenho>();
        }
    
        public int DSK_ID { get; set; }
        public string DSK_Display { get; set; }
        public Nullable<System.DateTime> DSK_DataCadastro { get; set; }
        public Nullable<System.DateTime> DSK_DataAlteracao { get; set; }
        public string DSK_Anotacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DES_Desempenho> DES_Desempenho { get; set; }
    }
}
