//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacao.Models.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP_Desemempenho
    {
        public int DSP_ID { get; set; }
        public int PER_ID { get; set; }
        public int USU_ID { get; set; }
        public string DSP_GrupoCompetidor { get; set; }
        public bool DSP_Target { get; set; }
        public double DSP_PayOut { get; set; }
        public long DSP_PontosPayOut { get; set; }
        public double DSP_Objetivo { get; set; }
        public double DSP_Realizado { get; set; }
        public long DSP_Pontos { get; set; }
        public long DSP_PontosTotais { get; set; }
        public int DSP_PosicaoRanking { get; set; }
        public System.DateTime DSP_DataCarga { get; set; }
        public bool DSP_Ativo { get; set; }
        public string DSP_Anotacao { get; set; }
        public string DSP_Ambiente { get; set; }
    
        public virtual PER_Periodos PER_Periodos { get; set; }
        public virtual USU_Usuario USU_Usuario { get; set; }
    }
}
