//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacao.Models.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_GrupoCompeticao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRC_GrupoCompeticao()
        {
            this.DES_Desempenho = new HashSet<DES_Desempenho>();
            this.RKG_RankingGrupo = new HashSet<RKG_RankingGrupo>();
        }
    
        public int GRC_ID { get; set; }
        public string GRC_Nome { get; set; }
        public string GRC_Display { get; set; }
        public Nullable<System.DateTime> GRC_DataCadastro { get; set; }
        public Nullable<System.DateTime> GRC_DataAlteracao { get; set; }
        public string GRC_Anotacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DES_Desempenho> DES_Desempenho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RKG_RankingGrupo> RKG_RankingGrupo { get; set; }
    }
}
