//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacao.Models.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAU_LogAutenticacaoUsuario
    {
        public int LAU_ID { get; set; }
        public string LAU_AcessoIP { get; set; }
        public string LAU_Ambiente { get; set; }
        public string LAU_DadosComplementares { get; set; }
        public Nullable<System.DateTime> LAU_DataCadastro { get; set; }
        public Nullable<int> USU_ID { get; set; }
    
        public virtual USU_Usuario USU_Usuario { get; set; }
    }
}
