//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacao.Models.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class PER_Periodos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PER_Periodos()
        {
            this.DSP_Desemempenho = new HashSet<DSP_Desemempenho>();
        }
    
        public int PER_ID { get; set; }
        public int PER_Mes { get; set; }
        public int PER_Ano { get; set; }
        public string PER_Nome { get; set; }
        public bool PER_Ativo { get; set; }
        public System.DateTime PER_DataCadastro { get; set; }
        public Nullable<System.DateTime> PER_DataAlteracao { get; set; }
        public string PER_Anotacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSP_Desemempenho> DSP_Desemempenho { get; set; }
    }
}
