//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacao.Models.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class RKG_RankingGrupo
    {
        public int RKG_ID { get; set; }
        public Nullable<int> GRC_ID { get; set; }
        public Nullable<int> USU_ID { get; set; }
        public int RKG_Posicao { get; set; }
        public double RKG_CriterioDesempate { get; set; }
        public Nullable<System.DateTime> RKG_DataCadastro { get; set; }
        public Nullable<System.DateTime> RKG_DataAlteracao { get; set; }
        public string RKG_Anotacao { get; set; }
    
        public virtual GRC_GrupoCompeticao GRC_GrupoCompeticao { get; set; }
        public virtual USU_Usuario USU_Usuario { get; set; }
    }
}
