//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacao.Models.ENTITY
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAN123_Entities : DbContext
    {
        public SAN123_Entities()
            : base("name=SAN123_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAR_Cargo> CAR_Cargo { get; set; }
        public virtual DbSet<DES_Desempenho> DES_Desempenho { get; set; }
        public virtual DbSet<DSD_DesempenhoDescricao> DSD_DesempenhoDescricao { get; set; }
        public virtual DbSet<DSF_DesempenhoFase> DSF_DesempenhoFase { get; set; }
        public virtual DbSet<DSK_DesempenhoKpi> DSK_DesempenhoKpi { get; set; }
        public virtual DbSet<GRC_GrupoCompeticao> GRC_GrupoCompeticao { get; set; }
        public virtual DbSet<RKG_RankingGrupo> RKG_RankingGrupo { get; set; }
        public virtual DbSet<USU_Usuario> USU_Usuario { get; set; }
        public virtual DbSet<LAU_LogAutenticacaoUsuario> LAU_LogAutenticacaoUsuario { get; set; }
    }
}
