//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacao.Models.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class USU_Usuario
    {
        public int USU_ID { get; set; }
        public int UNG_ID { get; set; }
        public string USU_Nome { get; set; }
        public string USU_CPF { get; set; }
        public string USU_Email { get; set; }
        public string USU_Celular { get; set; }
        public string USU_CodSac { get; set; }
        public string USU_Login { get; set; }
        public string USU_Senha { get; set; }
        public string USU_FotoPerfil { get; set; }
        public Nullable<System.DateTime> USU_DataAceite { get; set; }
        public bool USU_PrimeiroAcesso { get; set; }
        public bool USU_UsuarioTeste { get; set; }
        public bool USU_AcessoFake { get; set; }
        public bool USU_Ativo { get; set; }
        public System.DateTime USU_DataCadastro { get; set; }
        public Nullable<System.DateTime> USU_DataAlteracao { get; set; }
        public string USU_Anotacao { get; set; }
    
        public virtual UNG_UnidadeNegocio UNG_UnidadeNegocio { get; set; }
    }
}
